import React, { useState, useRef, useEffect } from 'react';
import {
  Copy, RefreshCw, Bookmark, ThumbsUp, ThumbsDown,
  Check, Play, MoreVertical, FileDown, Share2,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from 'jspdf';

/* ── Clipboard ───────────────────────────────────────────── */
function copyText(text) {
  if (navigator.clipboard) return navigator.clipboard.writeText(text);
  const el = Object.assign(document.createElement('textarea'), { value: text });
  document.body.appendChild(el); el.select();
  document.execCommand('copy'); document.body.removeChild(el);
}

/* ── PDF Export ──────────────────────────────────────────── */
function exportPDF(content) {
  const doc   = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const m     = 48;
  const maxW  = pageW - m * 2;
  let y = m;

  // Header bar
  doc.setFillColor(139, 92, 246);
  doc.rect(0, 0, pageW, 38, 'F');
  doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(255, 255, 255);
  doc.text('LUMINA AI — Response Export', m, 24);
  doc.setFontSize(8).setTextColor(220, 210, 255);
  doc.text(new Date().toLocaleDateString('en-IN', { dateStyle: 'long' }), pageW - m, 24, { align: 'right' });
  y = 64;

  const clean = content.replace(/---SOURCES---[\s\S]*/g, '').replace(/\*\*(.*?)\*\*/g, '$1').trim();

  for (const raw of clean.split('\n')) {
    if (y > pageH - m) { doc.addPage(); y = m; }
    const line = raw.trim();
    if (!line) { y += 8; continue; }

    if (line.startsWith('### ')) {
      doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(139, 92, 246);
      doc.splitTextToSize(line.slice(4), maxW).forEach(l => { doc.text(l, m, y); y += 18; });
      y += 4;
    } else if (line.startsWith('## ')) {
      doc.setFont('helvetica', 'bold').setFontSize(14).setTextColor(80, 50, 180);
      doc.splitTextToSize(line.slice(3), maxW).forEach(l => { doc.text(l, m, y); y += 21; });
      y += 6;
    } else if (/^[-•]/.test(line)) {
      doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(40, 40, 60);
      doc.splitTextToSize('•  ' + line.slice(2), maxW - 10).forEach(l => { doc.text(l, m + 8, y); y += 16; });
    } else {
      doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(40, 40, 60);
      doc.splitTextToSize(line, maxW).forEach(l => { doc.text(l, m, y); y += 16; });
    }
  }

  // Footer
  doc.setFont('helvetica', 'normal').setFontSize(8).setTextColor(160, 160, 180);
  doc.text('Generated by Lumina AI', pageW / 2, pageH - 18, { align: 'center' });
  doc.save(`lumina-${Date.now()}.pdf`);
}

/* ── Typing Bubble (exported for ChatInterface) ──────────── */
export function TypingBubble() {
  return (
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }} className="flex items-center gap-3.5">
      <div className="w-9 h-9 rounded-2xl flex items-center justify-center flex-shrink-0"
        style={{ background: 'linear-gradient(135deg,var(--primary),var(--secondary))', boxShadow: '0 4px 14px var(--glow)' }}>
        <span className="text-[10px] font-black text-white">LU</span>
      </div>
      <div className="flex items-center gap-1.5 px-4 py-3.5 rounded-2xl"
        style={{ background: 'var(--sidebar)', border: '1px solid var(--border)' }}>
        <div className="typing-dot w-2 h-2 rounded-full" style={{ background: 'var(--primary)' }} />
        <div className="typing-dot w-2 h-2 rounded-full" style={{ background: 'var(--primary)' }} />
        <div className="typing-dot w-2 h-2 rounded-full" style={{ background: 'var(--primary)' }} />
      </div>
    </motion.div>
  );
}

/* ============================================================
   MESSAGE BUBBLE
   ============================================================ */
export default function MessageBubble({ msg, onRegenerate, onSave, feedback, onFeedback }) {
  const [hovered,      setHovered]      = useState(false);
  const [copied,       setCopied]       = useState(false);
  const [shared,       setShared]       = useState(false);
  const [activeTab,    setActiveTab]    = useState('answer');
  const [showPdfMenu,  setShowPdfMenu]  = useState(false);
  const pdfRef = useRef(null);

  useEffect(() => {
    const h = (e) => { if (pdfRef.current && !pdfRef.current.contains(e.target)) setShowPdfMenu(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);

  const handleCopy = () => { copyText(msg.content); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  const handleShare = () => { copyText(msg.content); setShared(true); setTimeout(() => setShared(false), 2500); };

  /* ── User bubble ──────────────────────────────────────── */
  if (msg.role === 'user') {
    return (
      <motion.div initial={{ opacity: 0, x: 14 }} animate={{ opacity: 1, x: 0 }}
        transition={{ type: 'spring', stiffness: 340, damping: 28 }}
        className="flex justify-end w-full">
        <div className="max-w-[82%] px-5 py-4 rounded-[20px] rounded-tr-md"
          style={{ background: 'var(--sidebar)', border: '1px solid var(--border)' }}>
          <p className="text-[15px] leading-relaxed font-medium whitespace-pre-wrap"
            style={{ color: 'var(--text)' }}>
            {msg.content}
          </p>
        </div>
      </motion.div>
    );
  }

  /* ── Parse sources ──────────────────────────────────── */
  const [mainText, sourcesRaw = ''] = (msg.content || '').split('---SOURCES---').map(s => s.trim());
  const sources = sourcesRaw.split('\n').filter(l => l.includes(']('))
    .map(l => { const m = l.match(/\[(.*?)\]\((.*?)\)/); return m ? { title: m[1], url: m[2] } : null; })
    .filter(Boolean);
  const hasSources = sources.length > 0;

  /* ── Format body ──────────────────────────────────── */
  const renderBody = () => mainText.split('\n').map((line, i) => {
    const html = line
      .replace(/\*\*(.*?)\*\*/g, `<strong style="color:var(--primary-h);font-weight:700">$1</strong>`)
      .replace(/`([^`]+)`/g, `<code style="background:var(--code-bg);border:1px solid var(--code-border);color:var(--code-text);border-radius:5px;padding:0.1em 0.45em;font-family:JetBrains Mono,monospace;font-size:0.85em">$1</code>`);

    if (!html.trim()) return <div key={i} className="h-2.5" />;
    if (line.startsWith('### ') || line.startsWith('## '))
      return <h3 key={i} className="font-bold text-[15.5px] mt-5 mb-2"
        style={{ fontFamily: 'Poppins,sans-serif', color: 'var(--text)' }}
        dangerouslySetInnerHTML={{ __html: html.replace(/^#+\s/, '') }} />;
    if (/^[-•]\s/.test(line))
      return (
        <div key={i} className="flex items-start gap-2.5 mb-2">
          <span className="mt-[9px] w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: 'var(--primary)' }} />
          <p className="text-[15px] leading-relaxed" style={{ color: 'var(--text)' }}
            dangerouslySetInnerHTML={{ __html: html.replace(/^[-•]\s/, '') }} />
        </div>
      );
    return <p key={i} className="text-[15px] leading-[1.78] mb-3.5 last:mb-0"
      style={{ color: 'var(--text)' }} dangerouslySetInnerHTML={{ __html: html }} />;
  });

  /* ── AI bubble ────────────────────────────────────── */
  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
      transition={{ type: 'spring', stiffness: 290, damping: 26 }}
      className="flex items-start gap-4 w-full"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}>

      {/* Avatar */}
      <div className="w-9 h-9 rounded-2xl flex items-center justify-center flex-shrink-0 mt-0.5"
        style={{ background: 'linear-gradient(135deg,var(--primary),var(--secondary))', boxShadow: '0 4px 14px var(--glow)' }}>
        <span className="text-[10px] font-black text-white">LU</span>
      </div>

      <div className="flex-1 min-w-0">

        {/* ── Answer / Links tab bar ──────────────────── */}
        <div className="flex items-center gap-4 mb-4 pb-1"
          style={{ borderBottom: '1px solid var(--border)' }}>
          {(['answer', ...(hasSources ? ['links'] : [])]).map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab)}
              className={`tab-underline pb-2 text-[12.5px] font-semibold capitalize transition-colors ${
                activeTab === tab ? 'active-tab' : ''
              }`}
              style={{ color: activeTab === tab ? 'var(--primary)' : 'var(--text-3)' }}>
              {tab === 'links' ? `Links (${sources.length})` : 'Answer'}
            </button>
          ))}

          {/* Three-dot menu */}
          <div className="relative ml-auto" ref={pdfRef}>
            <button onClick={() => setShowPdfMenu(v => !v)}
              className="p-1.5 rounded-lg transition-all"
              style={{
                opacity: hovered || showPdfMenu ? 1 : 0,
                color: 'var(--text-3)',
                background: showPdfMenu ? 'var(--chip-bg)' : 'transparent',
              }}>
              <MoreVertical size={14} />
            </button>
            <AnimatePresence>
              {showPdfMenu && (
                <motion.div initial={{ opacity: 0, scale: 0.93, y: -6 }}
                  animate={{ opacity: 1, scale: 1,    y: 0 }}
                  exit={{   opacity: 0, scale: 0.93, y: -6 }}
                  transition={{ duration: 0.14 }}
                  className="absolute right-0 top-full mt-1.5 w-44 rounded-2xl z-50 p-1.5 glass-dropdown">
                  <button onClick={() => { exportPDF(msg.content); setShowPdfMenu(false); }}
                    className="w-full flex items-center gap-3 px-3.5 py-2.5 text-[13px] font-semibold rounded-xl transition-all"
                    style={{ color: 'var(--text-2)' }}
                    onMouseEnter={e => { e.currentTarget.style.background = 'var(--chip-bg)'; e.currentTarget.style.color = 'var(--primary)'; }}
                    onMouseLeave={e => { e.currentTarget.style.background = 'transparent';    e.currentTarget.style.color = 'var(--text-2)'; }}>
                    <FileDown size={14} /> Export as PDF
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* ── Content pane ─────────────────────────────── */}
        <AnimatePresence mode="wait">
          {(activeTab === 'answer' || !hasSources) ? (
            <motion.div key="answer"
              initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -4 }} transition={{ duration: 0.16 }}>
              {renderBody()}
            </motion.div>
          ) : (
            <motion.div key="links"
              initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -4 }} transition={{ duration: 0.16 }}
              className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {sources.map((src, idx) => (
                <a key={idx} href={src.url} target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-3.5 p-3.5 rounded-2xl transition-all"
                  style={{ background: 'var(--sidebar)', border: '1px solid var(--border)' }}
                  onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--primary)'}
                  onMouseLeave={e => e.currentTarget.style.borderColor = 'var(--border)'}>
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                    style={{ background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.12)' }}>
                    <Play size={11} className="text-red-400 fill-red-400/20" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-[13px] font-semibold truncate" style={{ color: 'var(--text)' }}>{src.title}</p>
                    <p className="text-[10px] font-bold uppercase tracking-wider mt-0.5" style={{ color: 'var(--text-3)' }}>Video Guide</p>
                  </div>
                </a>
              ))}
            </motion.div>
          )}
        </AnimatePresence>

        {/* ── Action buttons ────────────────────────────── */}
        <div className="flex items-center gap-0.5 mt-5 transition-all duration-200"
          style={{ opacity: hovered ? 1 : 0, transform: hovered ? 'translateY(0)' : 'translateY(3px)' }}>
          {[
            { icon: copied ? <Check size={13}/> : <Copy size={13}/>,       label: copied  ? 'Copied!'  : 'Copy',       onClick: handleCopy,                             active: copied,         },
            { icon: <RefreshCw size={13}/>,                                  label: 'Regenerate',                         onClick: () => onRegenerate?.(msg.id),                                   },
            { icon: <ThumbsUp size={13}/>,                                   label: 'Helpful',                            onClick: () => onFeedback?.(msg.id,'like'),      active: feedback==='like'  },
            { icon: <ThumbsDown size={13}/>,                                 label: 'Not Clear',                          onClick: () => onFeedback?.(msg.id,'dislike'),   danger: true, active: feedback==='dislike' },
            { icon: shared ? <Check size={13}/> : <Share2 size={13}/>,      label: shared  ? 'Copied!'  : 'Share',      onClick: handleShare,                            active: shared,         },
            { icon: <Bookmark size={13}/>,                                   label: 'Save',                               onClick: () => onSave?.(msg),                                           },
          ].map((btn, i) => <ActionBtn key={i} {...btn} />)}
        </div>
      </div>

      {/* Share toast */}
      <AnimatePresence>
        {shared && (
          <motion.div initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0 }}
            className="fixed bottom-28 left-1/2 -translate-x-1/2 z-[200] text-[13px] font-semibold px-4 py-2.5 rounded-2xl shadow-xl toast"
            style={{ background: 'var(--text)', color: 'var(--bg)' }}>
            ✓ Copied to clipboard
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

/* ── Action Button ───────────────────────────────────────── */
function ActionBtn({ icon, label, onClick, active, danger }) {
  const [hov, setHov] = useState(false);
  return (
    <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
      onClick={onClick}
      onMouseEnter={() => setHov(true)}
      onMouseLeave={() => setHov(false)}
      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl text-[11.5px] font-semibold transition-all"
      style={{
        border: '1px solid',
        borderColor: active ? 'var(--chip-border)' : 'transparent',
        background:  active ? 'var(--chip-bg)' : hov ? 'var(--chip-bg)' : 'transparent',
        color: active ? 'var(--primary)'
             : danger && hov ? '#f87171'
             : hov ? 'var(--text)'
             : 'var(--text-3)',
      }}>
      {icon}
      <span className="hidden sm:inline">{label}</span>
    </motion.button>
  );
}
