# Generated by Django 5.2.3 on 2026-05-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, help_text='e.g. Computer Science', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='intelligence.college'),
        ),
    ]
